### ISSUE TITLE
Signature validation

### ISSUE THREAD

**Issue by janek26** [stackup-wallet/stackup#1006]
Hey, nice project!

While reviewing the code I noticed this code:

https://github.com/stackup-wallet/stackup/blob/d7e459bc6eb5ad19a41345780f6815f3874db7c0/apps/backup/src/services/verification.service.ts#L10-L36

I think instead of comparing the offchain recovered signer you should follow [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271). This way you cover the case where a smart contract wallet has changed signer (recovered)

In case the wallet is not deployed yet, you can fallback to `initOwner` as you do.

**Comment by hazim-j** [comment]
Hi @janek26, this will still cover the case where the wallet has changed signer since `getOwner(0)` will always return the current signer address. But you are right that following EIP-1271 here might still be a cleaner approach.

I've noted this down and will refactor it when we have the capacity 👍
